/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_shun_litematica_extra_SchematicNativeReader */

#ifndef _Included_dev_shun_litematica_extra_SchematicNativeReader
#define _Included_dev_shun_litematica_extra_SchematicNativeReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_shun_litematica_extra_SchematicNativeReader
 * Method:    V7_To_V6
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_shun_litematica_extra_SchematicNativeReader_V7_1To_1V6
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
