name: C/C++ CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        target: [native, android]
        exclude:
          - os: windows-latest
            target: android
          - os: macos-latest
            target: android
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Setup MSVC (Windows)
        if: runner.os == 'Windows' && matrix.target == 'native'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup GCC (Linux)
        if: runner.os == 'Linux' && matrix.target == 'native'
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Setup Clang (macOS)
        if: runner.os == 'macOS' && matrix.target == 'native'
        run: |
          brew install llvm
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
        shell: bash

      - name: Setup Android NDK (Linux)
        if: runner.os == 'Linux' && matrix.target == 'android'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d

      # Windows: MSVC (MSBuild)
      - name: Build (Windows)
        if: runner.os == 'Windows' && matrix.target == 'native'
        run: cmake-build.bat
        shell: cmd

      # Linux: GCC
      - name: Build (Linux)
        if: runner.os == 'Linux' && matrix.target == 'native'
        run: |
          chmod +x cmake-build-linux.sh
          ./cmake-build-linux.sh
        shell: bash

      # macOS: Clang
      - name: Build (macOS)
        if: runner.os == 'macOS' && matrix.target == 'native'
        run: |
          chmod +x cmake-build-macos.sh
          ./cmake-build-macos.sh
        shell: bash

      # Android: Linux Android NDK
      - name: Build for Android
        if: runner.os == 'Linux' && matrix.target == 'android'
        run: |
          chmod +x cmake-build-android.sh
          ./cmake-build-android.sh
        shell: bash

      - name: List Dir (Unix)
        if: runner.os != 'Windows'
        run: find . -type f | sort

      - name: List Dir (Windows)
        if: runner.os == 'Windows'
        run: |
          (Get-ChildItem -Recurse -File).FullName | Sort-Object
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: all-artifacts
          path: artifacts/
          if-no-files-found: error
